### PR TITLE
Microsoft sentinel plugin

### PR DESCRIPTION
**Pull request by dobarx**

### CODE REVIEW

**Comment by traut** [comment]
@dobarx is this pull erquest one blocked by something? it's been in draft for a while now!

**Comment by dobarx** [comment]
@traut I needed to setup account to test with real API. I remember having some issues with it at the time. Will resume this and move to ready.

**Comment by traut** [comment]
oh, just noticed -- @dobarx could you please rename the plugin to `microsoft`? It's a better name to group future other sources / publishers that work with Microsoft services together

**Review by traut — APPROVED** [review]
🚀

**Comment by traut** [comment]
fixes https://github.com/blackstork-io/fabric/issues/129

**Pull request merged**
