### PR TITLE
`v0.3` plugins

### PR DESCRIPTION
**Pull request by dobarx**
All plugins from `v0.3` milestone:
- [x] #55 
- [x] #67 
- [x] #64   
- [x] #56 At this moment cannot load headers that are ahead of `toc` block. This should be solved with #98.
- [ ] #54 Completed according to the specs but not tested with real API yet. 

Other:
- All data sources that return lists started to fail after previous PR. I've changed now expected result type of data source in `parser` from `plugin.MapData` to `plugin.Data`. 
  @Andrew-Morozko Verify if this does not cause any issues with `parser`. (commit: 375015e)

### CODE REVIEW

**Review by traut — APPROVED** [review]

**Comment by traut** [comment]
it's funny that the CI checks do not re-run when the pull request becomes ready for review

**Comment by dobarx** [comment]
> it's funny that the CI checks do not re-run when the pull request becomes ready for review

It seems github actions trigger only on git events. Changing from draft to regular PR doesn't effect that.

**Comment by Andrew-Morozko** [comment]
Fixed this in #106

**Comment by Andrew-Morozko** [comment]
>   @Andrew-Morozko Verify if this does not cause any issues with `parser`. (commit: [375015e](https://github.com/blackstork-io/fabric/commit/375015e2f75b5a4f61fdf3f6a28c5c6881fd27ab))

@dobarx Done, everything is OK

**Pull request merged**
