### PR TITLE
Fix tests on windows and fuzzer

### PR DESCRIPTION
**Pull request by Andrew-Morozko**

### CODE REVIEW

**Comment by traut** [comment]
thank you very much for the fix, @Andrew-Morozko !

**Review by traut — APPROVED** [review]

**Comment by traut** [comment]
should we get this in, @Andrew-Morozko or not yet?

**Comment by Andrew-Morozko** [comment]
Ah, yep, still one test to debug. I'll try to get this finished today

**Comment by Andrew-Morozko** [comment]
Ok, merging it in @traut 

Our test was failing due to a bug in golang sqlite driver. It was _**extremely annoying to debug**_. I guess that's on me for assuming that popular databases are stable and well-tested pieces of software 😡

**Pull request merged**
